server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: VEHICLE-SERVICE
            uri:  lb://VEHICLE-SERVICE
            predicates:
              - Path=/vehicle/**
          - id: USER-SERVICE
            uri:  lb://USER-SERVICE
            predicates:
              - Path=/user/**
          - id: TICKET-SERVICE
            uri: lb://TICKET-SERVICE
            predicates:
              - Path=/ticket/**
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
